language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_3277cdc4c0fa_key -iv $encrypted_3277cdc4c0fa_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
install:
- npm install
- npm run test
script:
- echo "Skipping tests"
addons:
  ssh_known_hosts: 47.99.102.212
after_success:
- ssh root@47.99.102.212 'cd /data/node/koa-travis/ && git pull && export PATH=/root/nvm/versions/node/v10.15.1/bin:$PATH && npm install && npm run prd'
